moe-serifu-circle/moe-serifu-agent

python/msa/config.py, python/tests/test.cfg
made the output less randomly ordered by sorting the keys and sections by name
all saved files will be sorted alphanumerically
=> Gave config.save() a more consistant output

.drone.yml
This adds a new Drone pipeline for testing the current C++ codebase.
=> Added new .drone.yml

python/msa/__main__.py, python/msa/remote/client.py, python/msa/remote/server.py
Adds the ability to specify the client and server host and port params via the cli
=> Asyncio configure client server host

python/Pipfile, python/Pipfile.lock, python/msa/__main__.py, python/msa/builtins/help/coroutine.py, python/msa/builtins/terminal_input/coroutine.py, python/msa/remote/client.py, python/msa/remote/generic_producer_consumer.py, python/msa/remote/server.py, python/msa/supervisor.py
Replaces basic prompt with prompt_toolkit to enable command history
=> basic prompt_toolkit usage to add history

README.md
=> First test of drone; updated badge location

python/msa/var.py, python/tests/ConfigTest.py, python/tests/ExpanderTest.py
Closes Issue #49
Implementation is mostly consistent with c++ version. External variables were renamed to protected variables to more clearly describe their purpose. Escapes other than "\\" and "\$" are also now allowed as escapes just signal to the processor to ignore the proceeding character letting strings like "\h" process into "h"
Test file is also included
=> added Expander class in var.py (Closes Issue #49)

.drone.yml
=> Added execution of python tests to drone to close #48

.drone.yml, python/Pipfile, python/Pipfile.lock, python/msa/builtins/time/handlers.py, python/msa/builtins/tty/__init__.py, python/msa/builtins/tty/events.py, python/msa/builtins/tty/handlers.py, python/msa/core/event_bus.py, python/msa/core/loader.py, python/msa/core/supervisor.py, python/tests/async_test_util.py, python/tests/builtins/tty/handlers_test.py, python/tests/core/event_bus_test.py, python/tests/core/event_handler_test.py
=> Issue 92 - Creates TTY module, adds TtyInputHandler

python/msa/core/supervisor.py
Implements a graceful shutdown on ctrl -c by handling the keyboard interrupt error.
Ctrl-c triggers a keyboard interrupt error
The app handles the keyboard interrupt error, notifying the user of the shutdown, then gracefully shutting down all tasks and exits the supervisor.
No.
N/A
=> More graceful shutdown

.drone.yml, python/msa/builtins/command_registry/__init__.py, python/msa/builtins/command_registry/events.py, python/msa/builtins/command_registry/handlers.py, python/msa/builtins/time/handlers.py, python/msa/builtins/tty/handlers.py, python/msa/core/loader.py, python/msa/core/supervisor.py, python/tests/builtins/command_registry/handlers_test.py
=> Command registry and help

python/msa/builtins/echo/__init__.py, python/msa/builtins/echo/events.py, python/msa/builtins/echo/handlers.py, python/msa/core/loader.py, python/tests/builtins/echo/handlers_test.py
=> Created Echo Command

python/msa/builtins/command/__init__.py, python/msa/builtins/command/events.py, python/msa/builtins/command/handlers.py, python/msa/builtins/echo/__init__.py, python/msa/core/loader.py, python/msa/core/supervisor.py, python/tests/builtins/command/handlers_test.py
=> full quit dev + minor fixes

.drone.yml, python/Pipfile, python/Pipfile.lock, python/msa/__main__.py, python/msa/builtins/tty/handlers.py, python/msa/builtins/tty/prompt.py, python/msa/core/event_handler.py, python/msa/core/supervisor.py, python/tests/builtins/command/handlers_test.py, python/tests/builtins/command_registry/handlers_test.py, python/tests/builtins/echo/handlers_test.py, python/tests/builtins/tty/handlers_test.py, python/tests/core/event_bus_test.py, python/tests/expander_test.py
Removes prompt_toolkit dependency as it was ultimately making more problems than it was solving.
=> Fixes various tty issues with windows and various errors.

README.md
docs update
current build badge points to old CI server.
badge points to new CI server
None
=> Updated links in readme to point to new build server

python/sphinx/configuration.md
=> Adds config file documentation

python/msa/core/config_manager.py, python/msa/core/supervisor.py, python/msa_config.json, python/sphinx/configuration.md
=> Adds truncate_log_file config

python/msa/builtins/tty/handlers.py, python/sphinx/conf.py, python/sphinx/getting_started.md, python/tests/builtins/command/handlers_test.py, python/tests/builtins/command_registry/handlers_test.py, python/tests/builtins/echo/handlers_test.py, python/tests/builtins/tty/handlers_test.py, python/tests/core/event_handler_test.py
=> adds logging to tty module

python/sphinx/configuration.md
fixes table of contents levels. single # headings are inserted as a top-level topic in the TOC
There are several single # headings in the configuration documentation which polute the Table of Contents (TOC). This PR fixes the TOC.
=> fixes table of contents levels. single # headings are inserted as a top-level topic in the TOC

python/sphinx/conf.py
fixes the sphinx doc's reported version
Version is stated as 1.0, when it should say 0.1
Version is now set to 0.1
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)https://media.readthedocs.org/pdf/moe-serifu-agent/latest/moe-serifu-agent.pdfNo
=> Set correct version for 0.1 release

.github/ISSUE_TEMPLATE/bug_report.md
Removes unnecessary fields from the bug report template, as currently they are not relevant.
Bug report template asks for smartphone OS, Desktop browser...
Bug report template only asks the OS and version of moe-serifu-agent where the bug was found.
No
None
=> Remove unnecessary fields from bug reports

python/sphinx/getting_started.md
=> fixes broken links on getting started

.github/pull_request_template.md
- Issue: N/A
---
Adds the CLA to the PR template
No reminder to sign the CLA
Adds the CLA to the PR template
No
N/A
=> adds cla to pr

python/sphinx/contributor_guide.md, python/sphinx/getting_started.md, python/sphinx/using_the_cli.md
- Issue: 
---
Updates the installation instructions to use poetry instead of pipenv.
N/A
N/A
N/A
N/A
---
❗️🖊   If you have not yet, please sign our [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSfJPpwIv8MJkzxj41zBhnBDkrziQr9Tn_Z8hl5fRyY0xZnDuQ/viewform). 
Your PR will not be accepted until we have confirmed that you have signed.
=> update installation instructions to use poetry
